package.json, packages/api-gateway/src/drivers/http/adapters/usuarios/handlers.js, packages/api-gateway/src/drivers/http/routes/usuarios/index.js, packages/api-gateway/src/drivers/http/routes/usuarios/schema/index.js, packages/api-gateway/src/drivers/http/utils/errorHandler.js, yarn.lock
This pr solves the schemas needed to validate data usuarios from client
=> feat: create schemas to validate data from client

packages/usuario/src/domains/index.js, packages/usuario/src/domains/usuarios.js, packages/usuario/src/index.js, packages/usuario/src/useCases/index.js, packages/usuario/src/useCases/usuarios.js
This pr solves the issue #12 to update users in database
=> feat: create update method in usuarios package

packages/api-gateway/src/drivers/http/adapters/usuarios/handlers.js, packages/api-gateway/src/drivers/http/server.js, packages/api-gateway/src/drivers/http/utils/errorHandler.js
This pr is to add logger to visualize in a better format the logs of the api-gateway
=> refactor: add logger to api-gateway

.eslintrc.js, packages/core/src/drivers/db/models/file.js, packages/files/README.md, packages/files/__tests__/files.test.js, packages/files/jest.config.js, packages/files/package.json, packages/files/src/domains/files.js, packages/files/src/domains/index.js, packages/files/src/index.js, packages/files/src/useCases/files.js, packages/files/src/useCases/index.js, packages/files/src/utils/constants.js, packages/files/src/utils/manageFiles.js, yarn.lock
=> feat: create files methods in files package to upload, findone and delete files

packages/core/src/drivers/db/CSVFiles/domicilios.csv, packages/core/src/drivers/db/CSVFiles/instituciones.csv, packages/core/src/drivers/db/CSVFiles/personas.csv, packages/core/src/drivers/db/CSVFiles/planteles.csv, packages/core/src/drivers/db/CSVFiles/usuarios.csv, packages/core/src/drivers/db/seeders/20220929142539-create-personas-seed.js, packages/core/src/drivers/db/seeders/20220929143020-create-usuarios-seed.js, packages/core/src/drivers/db/seeders/20220929143500-create-instituciones-seed.js, packages/core/src/drivers/db/seeders/20220929143646-create-planteles-seed.js
This pr is for seeders in data base
=> chore: add csv seeders

packages/api-gateway/src/drivers/http/routes/usuarios/schema/getAllUsuariosSchema.js, packages/core/src/drivers/db/models/diligencia.js, packages/usuario/src/useCases/db/find-all.users.use-cases.js
This pr is to add rol attributes in the response of the get users endpoint
=> chore: add attributes about the rol in getAllUsers method

packages/api-gateway/src/drivers/http/routes/usuarios/schema/properties/persona.js, packages/core/src/drivers/db/CSVFiles/personas.csv, packages/core/src/drivers/db/models/persona.js
This pr is to solve a forgotten field in persona model
=> fix: add field tituloCargo to the persona model

packages/api-gateway/src/drivers/http/adapters/planteles/handlers/delete.handlers.plantel-infraestructura.adapters.js, packages/api-gateway/src/drivers/http/adapters/planteles/handlers/index.js, packages/api-gateway/src/drivers/http/routes/planteles/index.js, packages/api-gateway/src/drivers/http/routes/planteles/schema/delete.plantel-infraestructura.js, packages/api-gateway/src/drivers/http/routes/planteles/schema/index.js, packages/solicitudes/src/adapters/db/planteles/planteles.db.adapters.js, packages/solicitudes/src/use-cases/db/planteles/delete.plantel-infraestructura.use-cases.js, packages/solicitudes/src/use-cases/db/planteles/index.js, packages/solicitudes/src/use-cases/index.js
endpoint sdt-138 delete infraestructura, if you need me to modify anything let me know.
=> feat: (Delete Infraestructura) now able to delete infraestructura

packages/api-gateway/src/drivers/http/adapters/solicitudes/handlers/index.js, packages/api-gateway/src/drivers/http/adapters/solicitudes/handlers/update.handlers.seccion-observacion.adapters.js, packages/api-gateway/src/drivers/http/routes/solicitudes/index.js, packages/api-gateway/src/drivers/http/routes/solicitudes/schema/index.js, packages/api-gateway/src/drivers/http/routes/solicitudes/schema/update.seccion-observacion.schema.js, packages/solicitudes/src/adapters/db/solicitudes/solicitudes.db.adapters.js, packages/solicitudes/src/use-cases/db/solicitudes/index.js, packages/solicitudes/src/use-cases/db/solicitudes/update.seccion-observacion.use-cases.js, packages/solicitudes/src/use-cases/index.js
Si no se crea se actualiza asi
=> feat: (Solicitud Seccion Observacion) solicitudSeccionObservacion

jest-e2e.json
=> Update time jest-e2e.json

packages/api-gateway/src/drivers/http/adapters/index.js, packages/api-gateway/src/drivers/http/adapters/notificaciones/handlers/delete.handlers.notificaciones.adapters.js, packages/api-gateway/src/drivers/http/adapters/notificaciones/handlers/find-group.handlers.notificaciones.adapters.js, packages/api-gateway/src/drivers/http/adapters/notificaciones/handlers/find-one.handlers.notificaciones.adapters.js, packages/api-gateway/src/drivers/http/adapters/notificaciones/handlers/index.js, packages/api-gateway/src/drivers/http/routes/notificaciones/index.js, packages/api-gateway/src/drivers/http/routes/notificaciones/schemas/delete.notificaciones.schema.js, packages/api-gateway/src/drivers/http/routes/notificaciones/schemas/find-group.notificaciones.schema.js, packages/api-gateway/src/drivers/http/routes/notificaciones/schemas/find-one.notificaciones.schema.js, packages/api-gateway/src/drivers/http/routes/notificaciones/schemas/index.js, packages/api-gateway/src/drivers/http/routes/notificaciones/schemas/properties/notificaciones.js, packages/api-gateway/src/drivers/http/routes/notificaciones/schemas/properties/responseProperties.js, packages/notificaciones/src/adapters/db/notificaciones/notificaciones.db.adapters.js, packages/notificaciones/src/useCases/db/notificaciones/delete.notificacion.use-cases.js, packages/notificaciones/src/useCases/db/notificaciones/find-group.notificacion.use-cases.js, packages/notificaciones/src/useCases/db/notificaciones/find-one.notificacion.use-cases.js, packages/notificaciones/src/useCases/db/notificaciones/index.js, packages/notificaciones/src/useCases/index.js
**Descripción:**  
Se requiere el desarrollo de una serie de funcionalidades relacionadas con la tabla "notificaciones" y sus respectivos endpoints en la API. A continuación, se detallan los campos de la tabla y los endpoints necesarios:  
**Tabla "notificaciones" (YA EXISTE)**
-   **id**: Identificador único de la notificación.
-   **usuario_id**: Identificador del usuario al que se le envía la notificación (entero).
-   **asunto**: Asunto de la notificación (cadena de texto).
-   **template**: Plantilla utilizada para generar el contenido de la notificación (cadena de texto).
-   **email**: Dirección de correo electrónico a la que se enviará la notificación (cadena de texto).
-   **status**: Estado de la notificación, que puede ser "PENDING," "OPENED," o "SENT."
-   **data**: Datos …
=> Desarrollo de Endpoints para Notificaciones - Sdt 373

packages/core/src/drivers/db/models/programa.js
cambio de string a text por los campos de texto amplio
=> SDT-391 corrección tipo de datos en la Tabla programas

packages/api-gateway/package.json, packages/api-gateway/src/drivers/http/adapters/files/handlers.js, packages/api-gateway/src/drivers/http/routes/auth/schema/loginSchema.js, packages/api-gateway/src/drivers/http/routes/files/index.js, packages/api-gateway/src/drivers/http/routes/files/schema/delete.files.schema.js, packages/api-gateway/src/drivers/http/routes/files/schema/find.files.schema.js, packages/api-gateway/src/drivers/http/routes/files/schema/properties/files.js, packages/api-gateway/src/drivers/http/routes/files/schema/update.files.schema.js, packages/api-gateway/src/drivers/http/server.js, packages/api-gateway/src/drivers/http/utils/swaggerConfig.js, packages/files/src/adapters/fs/files/create.files.adapters.js, packages/files/src/adapters/fs/path-exist.fs.adapters.js, packages/files/src/useCases/db/files/create.files.db.use-cases.js, packages/files/src/useCases/db/files/delete.files.db.use-cases.js, packages/files/src/useCases/db/files/find-one.files.db.use-cases.js, packages/files/src/useCases/db/files/index.js, packages/files/src/useCases/db/files/update.files.db.use-cases.js, yarn.lock
Este pull request introduce una serie de mejoras y correcciones para la visualización y manejo de archivos en Swagger, así como actualizaciones en los casos de uso relacionados.
-   **Actualización de Swagger a OpenAPI 3.0**: Se actualizó la especificación de Swagger de nuestra API a la versión 3.0 para aprovechar las mejoras en la documentación de endpoints y compatibilidad con herramientas modernas.
-   **Reemplazo de `multer` por `@fastify/multipart`**: Para mejorar la integración con Swagger y aprovechar las capacidades de `@fastify/multipart`, se reemplazó `multer` por este último, proporcionando una mejor experiencia y soporte dentro del ecosistema Fastify.
-   **Adición de Esquemas para Operaciones CRUD**: Se añadieron y actualizaron esquemas para las operaciones `Update`, `Find` y …
=> Actulizacion de Files y Swagger

packages/api-gateway/src/drivers/http/routes/instituciones/schema/find-all.instituciones.schema.js, packages/api-gateway/src/drivers/http/routes/planMaestro/schemas/create.datos.schema.js, packages/api-gateway/src/drivers/http/routes/planMaestro/schemas/find-one.datos.schema.js, packages/api-gateway/src/drivers/http/routes/planMaestro/schemas/properties/tipoDeProyecto.js, packages/core/src/drivers/db/CSVFiles/tipo_proyectos.csv, packages/core/src/drivers/db/migrations/20220718180952-create-usuarios-table.js, packages/core/src/drivers/db/models/index.js, packages/core/src/drivers/db/models/proyecto.js, packages/core/src/drivers/db/models/proyectoTipoProyecto.js, packages/core/src/drivers/db/models/tipoProyecto.js, packages/core/src/drivers/db/seeders/20231129054358-create-tipo-proyecto-seed.js, packages/instituciones/src/useCases/db/instituciones/find-all.instituciones.use-cases.js, packages/opd/src/adapters/db/planesMaestros/planesMaestros.db.adapter.js, packages/opd/src/use-cases/db/planMaestro/create.datos-de-proyecto.use-case.js, packages/opd/src/use-cases/db/planMaestro/find-one.datos-plan-maestro.use-case.js, packages/opd/src/use-cases/db/planMaestro/index.js
---
Desarrollar la actualizacion de  la tabla tipoProyecto para un mejor manejo de datos. Añadiendo tablas intermedias.
- **POST  planMaestro/datosDelProyecto/{planMaestroId}**
- Este endpoint crea los datos generales de un  proyecto de un plan maestro.
- **GET planMaestro/datosDelProyecto/{planMaestroId}**
- Recuperar una lista de los datos generales de un  proyecto de un plan maestro identificado por el ID del plan maestro.
1. **tipo_proyectos(Model)**
- Hacer una tabla con los datos estaticos de tipos de proyectos.
- Debe de estar asociada con proyectos_tipo_proyectos.
```js
{
"id": "ID_DEL_PROYECTO",
"nombre": "NOMBRE_DEL_PROYECTO",
"descripcion": "DESCRIPCION_DEL_PROYECTO",
}
```
2. **proyectos_tipo_proyectos(Model)**
- Hacer una tabla que sirva  como intermediario entre proyecto y …
=> Fix OPD tabla tipoProyecto

packages/api-gateway/src/drivers/http/routes/docentes/schema/create.docente.schema.js, packages/api-gateway/src/drivers/http/routes/docentes/schema/find-one.docente.schema.js, packages/api-gateway/src/drivers/http/routes/docentes/schema/properties/formacion.js, packages/api-gateway/src/drivers/http/routes/docentes/schema/properties/formacionDocente.js, packages/api-gateway/src/drivers/http/routes/docentes/schema/update.docente.schema.js, packages/core/src/drivers/db/migrations/20220718180952-create-usuarios-table.js, packages/core/src/drivers/db/models/docente.js, packages/core/src/drivers/db/models/formacionesDocentes.js, packages/core/src/drivers/db/models/index.js, packages/solicitudes/src/adapters/db/docentes/docente.db.adapter.js, packages/solicitudes/src/use-cases/db/docentes/create.docente.use-cases.js, packages/solicitudes/src/use-cases/db/docentes/find-one.docente.use-cases.js, packages/solicitudes/src/use-cases/db/docentes/index.js, packages/solicitudes/src/use-cases/db/docentes/update.docente.use-cases.js
---
Desarrollar la actualizacion de  la nueva caracteristica que implica crear la tabla formacionesDocentes para un mejor manejo de datos. Esta actuara como una tabla intermedia entre la tabla formaciones y docentes.
- **POST  /api/v1/docentes/**
- Este endpoint crea los datos generales de un Docente.
- Se implementara un array de objetos que incluira las formaciones del docente
- **PATCH  /api/v1/docentes/{docenteId}**
- Este endpoint actualiza los datos generales de un Docente.
- Se implementara un array de objetos que incluira las formaciones del docente.
- **GET /api/v1/docentes/{docenteId}**
- Recuperar una lista de los datos generales de un Docente identificado por el ID del Docente.
- Adición formacionesDocentes junto la información de formaciones.
1. …
=> FEAT Formaciones Docentes / SDT-493

packages/notificaciones/src/useCases/services/templates/observacionSolicitud.html
Se requiere implementar una funcionalidad de confirmación al finalizar el llenado de observaciones en las solicitudes. El sistema debe preguntar al usuario si el llenado es correcto y ofrecer dos opciones predefinidas: "Sí" y "No". Dependiendo de la elección del usuario, la solicitud debe cambiar de estado de manera apropiada y mostrar las observaciones para su revisión y corrección si es necesario.
**Pasos para implementar**:
1.  Al finalizar el llenado de observaciones, presentar una ventana de diálogo o modal que pregunte al usuario: "¿El llenado es correcto?".
2.  Proporcionar dos botones con las respuestas: "Sí" y "No".
3.  Si el usuario selecciona "Sí", cambiar el estado de la solicitud a estado 3.
4.  Si el usuario selecciona "No", cambiar el estado de la solicitud a estado 200, …
=> Implementación de confirmación y gestión de estado al finalizar el llenado de observaciones - SDT 524

packages/core/src/drivers/db/CSVFiles/estatus_solicitudes_folios.csv, packages/core/src/drivers/db/CSVFiles/tipo_documentos.csv, packages/core/src/drivers/db/CSVFiles/tipo_solicitudes_folios.csv, packages/core/src/drivers/db/migrations/20220718180952-create-usuarios-table.js, packages/core/src/drivers/db/models/estatusSolicitudFolio.js, packages/core/src/drivers/db/models/foja.js, packages/core/src/drivers/db/models/folioDocumentoAlumno.js, packages/core/src/drivers/db/models/index.js, packages/core/src/drivers/db/models/libro.js, packages/core/src/drivers/db/models/solicitudFolio.js, packages/core/src/drivers/db/models/solicitudFolioAlumno.js, packages/core/src/drivers/db/models/tipoDocumento.js, packages/core/src/drivers/db/models/tipoSolicitudFolio.js
=> SDT-585: creación de modelos necesarios para módulo de solicitud de folios

packages/api-gateway/src/drivers/http/adapters/solicitudes/handlers/create.handlers.domicilio-solicitud-programa.adapters.js, packages/api-gateway/src/drivers/http/adapters/solicitudes/handlers/index.js, packages/api-gateway/src/drivers/http/routes/solicitudes/index.js, packages/api-gateway/src/drivers/http/routes/solicitudes/schema/create.domicilio-programa.schema.js, packages/api-gateway/src/drivers/http/routes/solicitudes/schema/index.js, packages/solicitudes/src/adapters/db/solicitudes/solicitudes.db.adapters.js, packages/solicitudes/src/use-cases/db/solicitudes/create.solicitud-domicilio-programa.use-cases.js, packages/solicitudes/src/use-cases/db/solicitudes/index.js
Continuar con el desarrollo correspondiente a este nuevo tipo de solicitud  
En este ticket se creó el tipo de solicitud de refrendo → [![](https://sicyt-projects.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318)SDT-521: Modificar endpoint para crear solicitudes (POST) agregando opción REFRENDOIn Develop](https://sicyt-projects.atlassian.net/browse/SDT-521)
Flujo  
1- Seleccionar tipo de solicitud  
2- Seleccionar solicitud Origen  
3- Seleccionar Domicilio de Destino  
Módulos y secciones
- General
-   Diligencias
-   Rector
-   Director
- Plan de estudios
-   Datos del Plan de estudios
-   Fundamentación del plan de estudios
-   Asignaturas (Solo en modo vista)
-   Docentes
-   Trayectorias (Copiar, en blanco o solo modo vista? )
-   Ingreso y Egreso (Copiar, …
=> Nuevo tipo de solicitud: Cambio de domicilio

packages/files/src/useCases/db/FDP/find-one.FDP06.db.use-cases.js, packages/files/src/utils/pdfs/FDP06.js, packages/files/src/utils/pdfs/pdfHandler.js
=> SDT-581: fix: Cambios FDP06 y pdfHandler

packages/files/src/utils/pdfs/FDP02.js
=> SDT 581: fix: fechaVigencia formateada

packages/files/src/utils/pdfs/OFAD.js
=> SDT-606: fix: Ortografía en Oficio Admisorio.

packages/api-gateway/src/drivers/http/routes/usuarios/schema/getUsuarioDetalleSchema.js, packages/usuario/src/useCases/usuario/db/find-one.users-detail.use-cases.js
Se agregó el rol al consultar mi perfil.
=> SDT-648: fix: Agregar el rol al consultar mi perfil.

packages/core/src/drivers/db/CSVFiles/inspeccion_preguntas.csv
se añadieron comas, y alguna letra faltante.
=> SDT-597 otografia inspecciones

packages/api-gateway/src/drivers/http/routes/privates/instituciones/schema/find-all.tipoInstituciones.schema.js
=> SDT-717: fix: ID del tipoInstituciones.

packages/administracionAcademica/src/use-cases/db/programas/find-all.programas.use-cases.js, packages/administracionAcademica/src/use-cases/db/programas/index.js, packages/api-gateway/src/drivers/http/adapters/administracionAcademica/programas/handlers/find-all.handlers.programas.adapters.js, packages/api-gateway/src/drivers/http/routes/privates/programas/schema/find-all.programas.schema.js
Ya díganle a Luis que deje de eructar pls
=> SDT-754: feature: Find programas segun su acuerdoRvoe

packages/api-gateway/src/drivers/http/routes/publics/programas/index.js
=> SDT-754: fix: Public Endpoint programas

packages/api-gateway/src/drivers/http/adapters/institituciones/handlers/create-one.handlers.institucionesDgp.adapters.js, packages/api-gateway/src/drivers/http/adapters/institituciones/handlers/index.js, packages/api-gateway/src/drivers/http/routes/privates/instituciones/index.js, packages/api-gateway/src/drivers/http/routes/privates/instituciones/schema/create.institucionDgp.schema.js, packages/api-gateway/src/drivers/http/routes/privates/instituciones/schema/index.js, packages/api-gateway/src/drivers/http/routes/privates/instituciones/schema/properties/institucionesDgp.js, packages/core/src/drivers/db/migrations/20220718180952-create-usuarios-table.js, packages/core/src/drivers/db/models/index.js, packages/core/src/drivers/db/models/institucionDgp.js, packages/instituciones/src/adapters/db/index.js, packages/instituciones/src/useCases/db/instituciones/create-one.institucionesDgp.use-cases.js, packages/instituciones/src/useCases/db/instituciones/index.js, packages/instituciones/src/useCases/index.js
Se agregó la Tabla InstitucionDgp y el endpoint POST.
=> SDT-757: fix: institucionDgp tabla y endpoint POST.

packages/api-gateway/src/drivers/http/adapters/index.js, packages/api-gateway/src/drivers/http/adapters/paises/handlers/find-all.handlers.paises.adapters.js, packages/api-gateway/src/drivers/http/adapters/paises/handlers/index.js, packages/api-gateway/src/drivers/http/routes/publics/paises/index.js, packages/api-gateway/src/drivers/http/routes/publics/paises/schema/find-all.paises.schema.js, packages/api-gateway/src/drivers/http/routes/publics/paises/schema/index.js, packages/api-gateway/src/drivers/http/routes/publics/paises/schema/properties/pais.js, packages/api-gateway/src/drivers/http/routes/publics/paises/schema/properties/responseProperties.js, packages/instituciones/src/adapters/db/index.js, packages/instituciones/src/useCases/db/paises/find-all.paises.use-case.js, packages/instituciones/src/useCases/db/paises/index.js, packages/instituciones/src/useCases/index.js
ruta
http://localhost:3000/api/v1/public/paises/
muestra;
{
"data": [
{
"id": 1,
"nombre": "Andorra ",
"createdAt": "2022-02-22T11:03:56.000Z",
"updatedAt": "",
"deletedAt": ""
},
{
"id": 2,
"nombre": "Emiratos Árabes Unidos ",
"createdAt": "2022-02-22T11:03:56.000Z",
"updatedAt": "",
"deletedAt": ""
},
{
"id": 3,
"nombre": "Afganistán ",
"createdAt": "2022-02-22T11:03:56.000Z",
"updatedAt": "",
"deletedAt": ""
},
{
"id": 4,
"nombre": "Antigua y Barbuda ",
"createdAt": "2022-02-22T11:03:56.000Z",
"updatedAt": "",
"deletedAt": ""
},
etc....
=> SDT-859(Feat): endpoint para mostrar los paises

.github/workflows/test-ci.yml, __test__/usuarios.e2e.js, __test__/utils/fixtures/users.js, packages/api-gateway/src/drivers/http/adapters/auth/handlers/change-password.handlers.usuario.adapters.js, packages/api-gateway/src/drivers/http/adapters/auth/handlers/index.js, packages/api-gateway/src/drivers/http/adapters/auth/handlers/token-recovery-password.handlers.usuario.adapters.js, packages/api-gateway/src/drivers/http/routes/publics/auth/index.js, packages/api-gateway/src/drivers/http/routes/publics/auth/schema/changePasswordByMailSchema.js, packages/api-gateway/src/drivers/http/routes/publics/auth/schema/changePasswordByUserIdSchema.js, packages/api-gateway/src/drivers/http/routes/publics/auth/schema/index.js, packages/api-gateway/src/drivers/http/routes/publics/auth/schema/tokenRecoveryPasswordSchema.js, packages/authentication/src/adapters/db/index.js, packages/authentication/src/adapters/strategies/auth.match-password.adapter.js, packages/authentication/src/use-cases/index.js, packages/authentication/src/use-cases/strategies/change-password.js, packages/authentication/src/use-cases/strategies/find-one.recovery-password.js, packages/authentication/src/use-cases/strategies/index.js, packages/authentication/src/use-cases/strategies/recovery-password.js, packages/core/src/drivers/db/migrations/20220718180952-create-usuarios-table.js, packages/core/src/drivers/db/models/index.js, packages/core/src/drivers/db/models/tokenRecoveryPassword.js, packages/notificaciones/config/environment.js, packages/notificaciones/src/index.js, packages/notificaciones/src/useCases/services/templates/changePassword.html, packages/notificaciones/src/useCases/services/templates/recoveryPassword.html
Se han realizado varias modificaciones para mejorar el manejo de contraseñas en el sistema de autenticación. Estos cambios incluyen nuevas funcionalidades para cambiar y recuperar contraseñas tanto por ID de usuario como por token enviado por correo.
---
1. **Archivo:** `__test__/usuarios.e2e.js`
- **Línea 17:** Se agregó la función `changePasswordByUserId` a las importaciones desde `'./utils/fixtures/users'`.
- **Línea 54:** Se añadió una nueva prueba para la ruta `[POST] /api/v1/auth/newPasswordToken`.
2. **Archivo:** `__test__/utils/fixtures/users.js`
- **Línea 70:** Se añadió un nuevo objeto `changePasswordByUserId` con detalles de prueba.
3. **Archivo Nuevo:** `packages/api-gateway/src/drivers/http/adapters/auth/handlers/change-password.handlers.usuario.adapters.js`
- Este archivo …
=> Cambio de contraseña - SDT 875

packages/api-gateway/src/drivers/http/adapters/solicitudesBecas/handlers/index.js, packages/api-gateway/src/drivers/http/adapters/solicitudesBecas/handlers/update.handlers.solicitud-beca-alumno.adapters.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesBecas/index.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesBecas/schema/index.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesBecas/schema/update.solicitud-beca-alumno.schema.js, packages/solicitudesBecas/src/adapters/db/solicitudesBecas/solicitudesBecas.db.adapters.js, packages/solicitudesBecas/src/use-cases/db/solicitudesBecasAlumnos/index.js, packages/solicitudesBecas/src/use-cases/db/solicitudesBecasAlumnos/update.solicitud-beca-alumno.use.case.js
Respuesta:
{
"data": {
"id": 1,
"solicitudBecaId": 1,
"estatusAlumnoBecaId": 1,
"tipoAlumnoBecaId": 1,
"alumnoId": 1,
"gradoId": 10,
"promedio": 8,
"porcentajeBeca": 80,
"createdAt": "2025-03-04T16:53:11.000Z",
"updatedAt": "2025-03-11T21:06:40.000Z",
"deletedAt": "",
"alumno": {
"id": 1,
"personaId": 10,
"situacionId": 1,
"programaId": 1,
"matricula": "matricula123",
"estatus": 1,
"adeudoMaterias": 0,
"descripcionEstatus": "",
"archivoCertificado": "",
"archivoNacimiento": "",
"archivoCurp": "",
"estatusCertificado": 1,
"estatusNacimiento": 1,
"estatusCurp": 1,
"observaciones1": "",
"observaciones2": "",
"fechaBaja": "2023-10-08T23:26:43.000Z",
"createdAt": "2023-10-08T23:26:43.000Z",
"updatedAt": "",
"deletedAt": ""
},
"grado": {
"id": 10,
"nombre": "Decimo cuatrimestre",
"descripcion": …
=> SDT-900(feat): Crear un ednpoint para actualizar un becas alumno

packages/usuario/src/useCases/usuario/db/find-one.user-users-principal.use-cases.js
Se agregó el checker para user users principal.
=> SDT-906: fix: Agregar checker para el user users principal

packages/files/src/adapters/db/FSE/fse.db.adapters.js, packages/files/src/useCases/db/FSE/find-one.Beca.db.use-cases.js, packages/files/src/useCases/db/FSE/index.js, packages/files/src/useCases/db/files/get-identifier-obj.files.db.use-cases.js, packages/files/src/utils/constants/tipo-documento.js, packages/files/src/utils/constants/tipo-entidad.js, packages/files/src/utils/pdfs/BECA.js, packages/files/src/utils/pdfs/index.js
Se creó el PDF para el Reporte de becas.
[BECA_1.pdf](https://github.com/user-attachments/files/19237937/BECA_1.pdf)
=> SDT-907: feat: PDF para el Reporte de Becas

packages/files/src/utils/pdfs/FDA01.js, packages/files/src/utils/pdfs/pdfHandler.js
[FDA01_solicitudId_9.pdf](https://github.com/user-attachments/files/19394798/FDA01_solicitudId_9.pdf)
=> SDT-919(feat): FDA01 listo

packages/api-gateway/src/drivers/http/adapters/solicitudesServSoc/handlers/delete.handlers.solicitud-serv-soc.adapters.js, packages/api-gateway/src/drivers/http/adapters/solicitudesServSoc/handlers/index.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/index.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/schema/delete.solicitud-serv-soc.schema.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/schema/index.js, packages/solicitudesServicioSocial/src/adapters/db/solicitudesServSoc/solicitudesServSoc.db.adapters.js, packages/solicitudesServicioSocial/src/use-cases/db/solicitudesServSoc/delete.solicitud-serv-soc-use-cases.js, packages/solicitudesServicioSocial/src/use-cases/db/solicitudesServSoc/index.js
=> SDT-916. Creación de endpoint para elimiar una solicitud de servicio social

packages/solicitudesServicioSocial/src/use-cases/db/solicitudesServSoc/create.solicitud-serv-soc.use-cases.js
=> SDT-923(refactor): se coprrigio el folio servicio social

packages/api-gateway/src/drivers/http/adapters/solicitudesServSoc/handlers/find-all.handlers.ejes-serv-soc.adapters.js, packages/api-gateway/src/drivers/http/adapters/solicitudesServSoc/handlers/index.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/index.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/schema/find-all.ejes-serv-soc.schema.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/schema/index.js, packages/solicitudesServicioSocial/src/adapters/db/solicitudesServSoc/solicitudesServSoc.db.adapters.js, packages/solicitudesServicioSocial/src/use-cases/db/solicitudesServSoc/find-all.ejes-serv-soc.use-cases.js, packages/solicitudesServicioSocial/src/use-cases/db/solicitudesServSoc/index.js
=> SDT-928(feat): findall ejes x dimenciones

packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/schema/find-all.solicitudes-serv-soc-alumnos.schema.js
{
"data": [
{
"id": 1,
"solicitudServicioSocialId": 1,
"alumnoId": 2,
"gradoId": 2,
"modalidadServicioSocialId": 2,
"sectorServicioSocialId": 2,
"ejeServicioSocialId": 2,
"lugarReceptor": "Escuela",
"fechaInicio": "2024-07-28",
"fechaTermino": "2024-07-28",
"alumno": {
"id": 2,
"personaId": 11,
"situacionId": 1,
"programaId": 1,
"matricula": "matricula234",
"estatus": 1,
"adeudoMaterias": 0,
"descripcionEstatus": "",
"archivoCertificado": "",
"archivoNacimiento": "",
"archivoCurp": "",
"estatusCertificado": 1,
"estatusNacimiento": 1,
"estatusCurp": 1,
"observaciones1": "",
"observaciones2": "",
"fechaBaja": "2023-10-08T23:26:43.000Z",
"createdAt": "2023-10-08T23:27:17.000Z",
"updatedAt": "",
"deletedAt": ""
},
"grado": {
"id": 2,
"nombre": "Segundo cuatrimestre",
"descripcion": "Segundo …
=> SDT-932(refactor) se agrego el id

packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/schema/find-all.solicitudes-serv-soc-alumnos.schema.js, packages/solicitudesServicioSocial/src/use-cases/db/solicitudesServSocAlumnos/find-all.solicitudes-serv-soc-alumnos.use-cases.js
{
"data": [
{
"id": 1,
"solicitudServicioSocialId": 1,
"alumnoId": 2,
"gradoId": 2,
"modalidadServicioSocialId": 2,
"sectorServicioSocialId": 2,
"ejeServicioSocialId": 2,
"lugarReceptor": "Escuela",
"fechaInicio": "2024-07-28",
"fechaTermino": "2024-07-28",
"createdAt": "2025-03-25T17:23:50.000Z",
"updatedAt": "",
"deletedAt": "",
"alumno": {
"id": 2,
"personaId": 11,
"situacionId": 1,
"programaId": 1,
"matricula": "matricula234",
"estatus": 1,
"adeudoMaterias": 0,
"descripcionEstatus": "",
"archivoCertificado": "",
"archivoNacimiento": "",
"archivoCurp": "",
"estatusCertificado": 1,
"estatusNacimiento": 1,
"estatusCurp": 1,
"observaciones1": "",
"observaciones2": "",
"fechaBaja": "2023-10-08T23:26:43.000Z",
"createdAt": "2023-10-08T23:27:17.000Z",
"updatedAt": "",
"deletedAt": "", …
=> SDT-932(refactor): se agrego personaid y los datos del mismo

packages/api-gateway/src/drivers/http/adapters/solicitudesBecas/handlers/update.handlers.solicitud-beca.adapters.js, packages/api-gateway/src/drivers/http/adapters/solicitudesServSoc/handlers/update.handlers.solicitud-serv-soc.adapters.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/schema/create.solicitud-serv-soc.schema.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/schema/properties/solicitudServicioSocial.js, packages/api-gateway/src/drivers/http/routes/privates/solicitudesServicioSocial/schema/update.solicitud-serv-soc.schema.js, packages/core/src/drivers/db/models/solicitudServicioSocial.js, packages/notificaciones/src/useCases/services/templates/observacionesSolicitudServicioSocial.html, packages/notificaciones/src/useCases/services/templates/reporteSolicitudServicioSocial.html, packages/solicitudesServicioSocial/src/use-cases/db/solicitudesServSoc/update.solicitud-serv-soc.use-cases.js
**_Creación de Notificación para Solicitud Servicio Social._**
**Dos templates.**
- Observaciones.
- Reporte Servicio Social.
**_IMPORTANTE_**
- Hacer migrations y seeds porque se agregó el campo _usuarioId_ a la tabla _solicitudServicioSocial_.
- Si se hace uso del endpoint POST para crear una Solicitud Servicio Social, se deberá agregar el usuarioId porque está marcado como requerido.
_Ejemplo de body:_
```
{
"estatusSolicitudServicioSocialId": 1,
"programaId": 1,
"cicloEscolarId": 2,
"usuarioId": 1,
"domicilio": {
"municipioId": 1,
"estadoId": 1,
"calle": "Si o que",
"numeroExterior": "1936",
"colonia": "Lazaro Cardenas",
"codigoPostal": 44490
}
}
```
=> SDT-931: feat: Notificación para Solicitud Servicio Social.

packages/api-gateway/src/drivers/http/adapters/solicitudesServSoc/handlers/find-all.handlers.solicitudes-serv-soc-alumnos.adapters.js, packages/solicitudesServicioSocial/src/use-cases/db/solicitudesServSocAlumnos/find-all.solicitudes-serv-soc-alumnos.use-cases.js
El endpoint solo era un find all no usaba el solicitudServicioSocialId para filtrar, se corrigió
=> SDT-935(refactor): se corrigio logica de endpoint

packages/administracionAcademica/src/adapters/db/programas/programa.db.adapter.js, packages/api-gateway/src/drivers/http/routes/privates/programas/schema/find-one.programa.schema.js, packages/api-gateway/src/drivers/http/routes/privates/programas/schema/properties/turno.js
const { programa } = require('../../solicitudes/schema/properties/programa');
const { plantel } = require('../../instituciones/schema/properties/plantel');
const { nivel } = require('../../grupos/schema/properties/nivel');
const { ciclo } = require('./properties/ciclo');
const { modalidad } = require('./properties/modalidad');
const { institucion } = require('../../instituciones/schema/properties/institucion');
const { domicilio } = require('../../usuarios/schema/properties/domicilio');
const { responseProperties } = require('../../instituciones/schema/properties/responseProperties');
const { turno } = require('./properties/turno');
const findOneProgramaSchema = {
tags: ['Programa'],
description: 'Return a Programa by providing a programaId.',
params: {
title: 'findOneProgramaSchema', …
=> SDT-962(refactor): se agrego el turno

packages/externalService/src/use-cases/db/alumnos/create.alumnos.use-cases.js, packages/externalService/src/use-cases/db/alumnos/inscripcion.alumnos.use-cases.js
La creación de los alumnos lo coló activos en la creación y se quitó la validación de que el alumno este activo en inscripción y se le quitó la validación de que el alumno tuviera la situación de validación en auténtica
=> SDT-1053(Refactor): se quito validacion de incripcion y se coloco alumnos activos

packages/files/src/adapters/php/formatos/fda02.php, packages/files/src/adapters/php/helpers/index.js, packages/files/src/useCases/db/FDA/build.FDA02.db.use-cases.js, packages/files/src/useCases/db/FDA/index.js, packages/files/src/useCases/db/FSE/build.HISOTIAL.db.use-cases.js, packages/files/src/useCases/features/build-file.helper.js
DOCUMENTO QUE ACREDITA SUS ESTUDIOS (No se encuentra).
[fda02_1_1753986852483.pdf](https://github.com/user-attachments/files/21535856/fda02_1_1753986852483.pdf)
=> SDT-1117: fix: FDA02 with PHP

packages/administracionAcademica/src/adapters/db/ciclosEscolares/ciclosEscolares.db.adapter.js, packages/administracionAcademica/src/use-cases/db/alumnos/find-one.alumno.use-cases.js, packages/administracionAcademica/src/use-cases/db/ciclosEscolares/create.ciclo-escolar.use-cases.js, packages/administracionAcademica/src/use-cases/db/ciclosEscolares/find-group.ciclo-escolar.use-cases.js, packages/administracionAcademica/src/use-cases/db/ciclosEscolares/index.js, packages/administracionAcademica/src/use-cases/db/ciclosEscolares/update.ciclo-escolar.use-cases.js, packages/api-gateway/src/drivers/http/routes/privates/alumnos/schema/find-one.alumno.schema.js, packages/api-gateway/src/drivers/http/routes/privates/alumnos/schema/properties/equivalencia.js, packages/core/src/drivers/db/models/alumno.js
Este PR introduce varios ajustes y mejoras en el módulo de equivalencias, principalmente para el manejo de la relación entre alumnos y equivalencias y la gestión de ciclos escolares. Se modificaron 9 archivos, con 44 líneas añadidas y 25 eliminadas.
---
1. **Modelo de Alumno**  
- Se agregó la relación hasOne con Equivalencia, permitiendo asociar una equivalencia a cada alumno.
```javascript
this.hasOne(models.Equivalencia, { as: 'equivalencia', foreignKey: 'alumnoId' });
```
2. **Schema de API Gateway**  
- Se añadió la propiedad equivalencia en la respuesta del endpoint de alumnos, incluyendo campos como alumnoId, folioExpediente, folioResolucion y fechaResolucion.
- Se creó el archivo `equivalencia.js` para definir la estructura de la equivalencia en el esquema de respuesta.
3. **Casos …
=> SDT-1123: Ajustes para modulo de equivalencias

packages/api-gateway/src/drivers/http/routes/privates/planteles/schema/properties/infraestructura.js, packages/api-gateway/src/drivers/http/routes/privates/planteles/schema/update.plantel-infraestructura.js, packages/core/src/drivers/db/models/infraestructura.js
[SDT-1153](https://sicyt-projects.atlassian.net/browse/SDT-1153) -> error en solicitudes
=> SDT-1153: Deploy to PROD

packages/files/src/adapters/php/formatos/fdp02.php
[SDT-1162](https://sicyt-projects.atlassian.net/browse/SDT-1162?atlOrigin=eyJpIjoiNjI2ZmVjOTVkNGNlNDU0M2I0N2U1MjQ2ZmYzY2E1MWQiLCJwIjoiaiJ9)
FDP02 special characters
=> SDT-1162: DEPLOY TO PROD

packages/files/src/adapters/php/formatos/fhistorial.php
[SDT-1186](https://sicyt-projects.atlassian.net/browse/SDT-1186?atlOrigin=eyJpIjoiNWNhZDRhY2E1N2IyNDQwNGE0OWIxNmYxZTg5NTk0YmEiLCJwIjoiaiJ9)
_**Kardex con un solo decimal en el promedio**_
=> SDT-1186: DEPLOY TO PROD

packages/administracionAcademica/src/use-cases/db/ciclosEscolares/delete.ciclo-escolar.use-cases.js, packages/administracionAcademica/src/use-cases/db/ciclosEscolares/find-group.ciclo-escolar.use-cases.js, packages/administracionAcademica/src/use-cases/db/ciclosEscolares/index.js, packages/api-gateway/src/drivers/http/adapters/ciclosEscolares/handlers/delete.handlers.ciclo-escolar.adapters.js
[SDT-1201](https://sicyt-projects.atlassian.net/browse/SDT-1201?atlOrigin=eyJpIjoiNWZlZGU5OTk5ODg0NDg2MmJiZmIxODJlYjMyMDc1MDkiLCJwIjoiaiJ9)
**_Se añadió botón de eliminación y mensajes alternativos en caso de tener grupos en ciclos escolares._**
=> SDT-1201: DEPLOY TO PROD

packages/files/src/adapters/php/formatos/fhistorial.php
[SDT-1217](https://sicyt-projects.atlassian.net/browse/SDT-1217?atlOrigin=eyJpIjoiNTgxYzE3MjdjYzllNDI5YzgwYzZjOTFkZTY3YjRkYjkiLCJwIjoiaiJ9)
**_Modificación de tablas por error de logotipos en el Kardex_**
=> SDT-1217: DEPLOY TO PROD

packages/files/src/adapters/php/formatos/fhistorial.php
[SDT-1218](https://sicyt-projects.atlassian.net/browse/SDT-1218?atlOrigin=eyJpIjoiYjA2MWMzODcyYmUwNGZlNDk3Y2Y3NzhlOTU1NTVkNzgiLCJwIjoiaiJ9)
**_Calificaciones cerradas con decimal en Kardex._**
=> SDT-1218: DEPLOY TO PROD
